[package]
name = "xp-md2html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "xpmd"
path = "src/bin/xpmd.rs"

[dependencies]
anyhow = "1.0.97"
comrak = { version = "0.56.0", default-features = false }
markdown = "1.0.0-alpha.16"
sha2 = "0.10"
tempfile = "3.8"
clap = { version = "4.4", features = ["derive"] }
ureq = "3.4.2"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
techxt = "0.1.0"
fancy-regex = "0.16"
yaml-rust2 = "0.13"
caseless = "0.2"

[dev-dependencies]
image-compare = "0.4"
image = "0.25"
